### ISSUE TITLE
Toast attaches to top view controller.

### ISSUE THREAD

**Issue by jamestapping** [PhilippeWeidmann/NotificationToast#11]
The view attaches to the top view controller which is obviously by design. But this means that if another controller comes into view modally, the view attaches to the top of it and can be pulled down with it. This isn't the behaviour of the native toast.
Sorry have no idea for a PR myself but I thought I'd mention it. Thanks!

**Comment by PhilippeWeidmann** [comment]
This is indeed the case and I don't know if it's possible to resolve this issue. I will leave it open if someone has an idea on how to fix this issue.

**Comment by iSapozhnik** [comment]
This issue might be solved by having a dedicated UIWindow just for the toast.

**Comment by timetraveler90** [comment]
![IMG_0054](https://user-images.githubusercontent.com/4432648/132697857-27eb523f-a465-4c99-8df1-7552d66dd24b.jpg)

Is this the reason why every time I take a screenshot I see the toast 'peaking' from the top of the screen or this is a different bug? :)

**Comment by PhilippeWeidmann** [comment]
Hi this is definitely a bug and I will take a look at it as soon as I can

**Comment by timetraveler90** [comment]
Thanks man, keep me updated, please

**Comment by PhilippeWeidmann** [comment]
Okay the lastest version should fix the problems mentionned in this issue. Now the ToastView displays itself in its own UIWindow so this means that it is no longer attached to the top view controller. I didn't add a lot of code but it's kind of a big change so tell me if something is broken (please create a new issue).
