### ISSUE TITLE
ToastViewWindow not show

### ISSUE THREAD

**Issue by ngodacdu** [PhilippeWeidmann/NotificationToast#15]
In my application,
I have the function to sign in with apple. 
Firstly, I touch up inside the sign in with apple button, the sign in form will show. Show ToastView after the sign in process is completed but nothing happens (the toast view not show).

```
private func singinError(message: String) {
        let toast = ToastView(title: message)
        toast.show(haptic: .error)
    }
```

I try to debug in the init func of ToastViewWindow
```
let scene = UIApplication.shared.connectedScenes.first(where: { $0.activationState == .foregroundActive }) as? UIWindowScene
```
At this time, activationState is foregroundInactive.
My opinion, we should add filter condition. It looks like:
```
let scene = UIApplication.shared.connectedScenes.first(where: { $0.activationState == .foregroundActive || $0.activationState == .foregroundInactive }) as? UIWindowScene
```
I will be happy if it is fixed.

Thanks!

**Comment by ngodacdu** [comment]
![Screen Shot 2021-10-07 at 12 11 31 AM](https://user-images.githubusercontent.com/3876384/136251801-f9f7ed97-c7da-4561-889f-f0a9c60b4781.png)

**Comment by PhilippeWeidmann** [comment]
Hello I think that we can indeed modify the view to show it on inactive scenes but we should only do it if no active scene was found first what do you think ?
```
if let scene = UIApplication.shared.connectedScenes.first(where: { $0.activationState == .foregroundActive }) as? UIWindowScene {
...
} else if let scene = UIApplication.shared.connectedScenes.first(where: { $0.activationState == .foregroundInactive }) as? UIWindowScene
...
} else {
...
}
```

**Comment by PhilippeWeidmann** [comment]
Done with release 1.1.1. (49b48f5117c7029637cd35b1179e6b703002246c)
