### ISSUE TITLE
Multiline subtitle text?

### ISSUE THREAD

**Issue by timetraveler90** [PhilippeWeidmann/NotificationToast#8]
I just faced a request where I'd need to show subtitle in two lines, is it possible to do it now or we should create a PR for it?

**Comment by PhilippeWeidmann** [comment]
You can create a PR and I will gladly review it

**Comment by iSapozhnik** [comment]
This is implemented within [this](https://github.com/PhilippeWeidmann/NotificationToast/pull/10) PR
