### ISSUE TITLE
Could the class handle the main thread itself ?

### ISSUE THREAD

**Issue by jamestapping** [PhilippeWeidmann/NotificationToast#9]
Thanks for a really useful tool , just a comment, I think it would be cool if the class handled the main thread part of things.
The show and the hide functions are easy to wrap in main async code but not the initializer. Is this possible ? thanks

**Comment by PhilippeWeidmann** [comment]
Hi, it's not a bad idea but I think that it is the developper's responsability to do UI calls on the UI thread (main thread). The behaviour is the same as Apple's own frameworks.
